{"uid":"80cfde4d4414e77b","name":"Тест: выход из аккаунта","fullName":"tests.personal_account_test.TestRestorePassword#test_logout","historyId":"2327d1e2f6d63044792a4617579497ef","time":{"start":1734771353092,"stop":1734771353093,"duration":1},"status":"broken","statusMessage":"TypeError: 'generator' object is not callable","statusTrace":"self = <personal_account_test.TestRestorePassword object at 0x000002469EFBB490>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"301ed5ed1e368cc50edb9aaa49f2f6e2\")>\npersonal_account = <pages.personal_account_page.PersonalAccountPage object at 0x000002469F0B8C20>\ntest_user_create = <generator object test_user_create at 0x000002469F087300>\n\n    @allure.title(\"Тест: выход из аккаунта\")\n    def test_logout(self, driver, personal_account, test_user_create):\n        # Авторизация\n        print(\"sssss\")\n>       print(test_user_create())\nE       TypeError: 'generator' object is not callable\n\ntests\\personal_account_test.py:43: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1734771348454,"stop":1734771353092,"duration":4638},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false},{"name":"test_user_create","time":{"start":1734771353092,"stop":1734771353092,"duration":0},"status":"passed","steps":[{"name":"Создание пользователя через api","time":{"start":1734771353092,"stop":1734771353092,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"attachmentStep":false,"hasContent":true},{"name":"personal_account","time":{"start":1734771353092,"stop":1734771353092,"duration":0},"status":"passed","steps":[{"name":"Открытие главной страницы","time":{"start":1734771353092,"stop":1734771353092,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"driver","value":"<selenium.webdriver.chrome.webdriver.WebDriver (session=\"301ed5ed1e368cc50edb9aaa49f2f6e2\")>"}],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":1,"attachmentStep":false,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"TypeError: 'generator' object is not callable","statusTrace":"self = <personal_account_test.TestRestorePassword object at 0x000002469EFBB490>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"301ed5ed1e368cc50edb9aaa49f2f6e2\")>\npersonal_account = <pages.personal_account_page.PersonalAccountPage object at 0x000002469F0B8C20>\ntest_user_create = <generator object test_user_create at 0x000002469F087300>\n\n    @allure.title(\"Тест: выход из аккаунта\")\n    def test_logout(self, driver, personal_account, test_user_create):\n        # Авторизация\n        print(\"sssss\")\n>       print(test_user_create())\nE       TypeError: 'generator' object is not callable\n\ntests\\personal_account_test.py:43: TypeError","steps":[],"attachments":[{"uid":"2b68e135968032a","name":"stdout","source":"2b68e135968032a.txt","type":"text/plain","size":6}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"stepsCount":0,"attachmentStep":false,"hasContent":true},"afterStages":[{"name":"driver::0","time":{"start":1734771353172,"stop":1734771355262,"duration":2090},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('personal_account')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"personal_account_test"},{"name":"subSuite","value":"TestRestorePassword"},{"name":"host","value":"DESKTOP-7LU8FN0"},{"name":"thread","value":"14652-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.personal_account_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('personal_account')"]},"source":"80cfde4d4414e77b.json","parameterValues":[]}